"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ui_logic_js_1 = require("./ui-logic.js");
var canvas_logic_js_1 = require("./canvas-logic.js");
var app = new canvas_logic_js_1.CanvasApp();
(0, ui_logic_js_1.setupUI)();
var addImg = document.getElementById("addBtn");
var clearImg = document.getElementById("clearBtn");
addImg.onclick = app.addRandomImg;
clearImg.onclick = app.clearCanvas;
var leftBtn = document.getElementById("leftBtn");
var rightBtn = document.getElementById("rightBtn");
var upBtn = document.getElementById("upBtn");
var downBtn = document.getElementById("downBtn");
leftBtn.addEventListener("click", function () { return app.moveImg(-10, 0); });
rightBtn.addEventListener("click", function () { return app.moveImg(10, 0); });
upBtn.addEventListener("click", function () { return app.moveImg(0, -10); });
downBtn.addEventListener("click", function () { return app.moveImg(0, 10); });
